server.port: 8080

debug: true

spring:
  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}

  jpa:
    show-sql: true

  flyway:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}

    mvc:
      log-request:
        details: true

app:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ujypdifcqancvg
    password: a3f628faaede6d3320c8c3dc63fa8c1d672ad9c51b336769621966074232a6f0

logging:
  level:
      org:
        springframework: DEBUG