spring.profiles.active: dev

spring:
  datasource:
    max-active: 10
    max-idle: 8
    min-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000

  jpa:
      hibernate.ddl-auto: validate
      properties.hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
      show-sql: true

  flyway:
      enable: true
      baseline-on-migrate: true
      baseline-version: 1
      driver-class-name: org.postgresql.Driver
      sql-migration-prefix: V
      sql-migration-separator: __
      sql-migration-suffixes: .sql
      locations: classpath:db/migration